export enum ActionType {
    post = 'post',
    removePost = 'removePost',
    like = 'like',
    unlike = 'unlike',
    comment = 'comment',
    reply = 'reply',
    repost = 'repost',
    repostWithThought = 'repostWithThought',
    follow = 'follow',
    unfollow = 'unfollow',
    followers = 'followers',
    unfollowers = 'unfollowers',
    createCollection = 'createCollection',
    mint = 'mint',
    list = 'list',
    bid = 'bid',
    buyNft = 'buyNft',
    sellNft = 'sellNft',
    profile = 'profile',
    kyc = 'kyc',
    affiliate = 'affiliate'
}
