export enum ENotificationFromType {
    APP = 'APP',
    USER = 'USER'
}

export enum NotificationType {
    MINTING = 'MINTING',
    BIDDING = 'BIDDING',
    LISTING = 'LISTING',
    FOLLOW = 'FOLLOW',
    SOLD = 'SOLD',
    BOUGHT = 'BOUGHT',
    REMOVE_BID = 'REMOVE_BID',
    STAGE = 'STAGE',
    REACTION = 'REACTION',
    REPOST = 'REPOST',
    COMMENT = 'COMMENT',
    COMMENT_REPLY = 'COMMENT_REPLY',
    MENTIONED = 'MENTIONED',
    VOTE = 'VOTE',
    Like = 'LIKE',
    Like_COMMENT = 'LIKE_COMMENT',
    Hashtag = 'HASHTAG',
    MESSAGE = 'MESSAGE',
    // SEND FOLLOWER NOTICE
    FOLLOWER_POST = 'FOLLOWER_POST',
    FOLLOWER_MINT = 'FOLLOWER_MINT',
    FOLLOWER_CREATE_COLLECTION = 'FOLLOWER_CREATE_COLLECTION',
    FOLLOWER_COMMENT = 'FOLLOWER_COMMENT',
    FOLLOWER_REPOST = 'FOLLOWER_REPOST',

    SYSTEM = 'SYSTEM'
}
