export enum ActivityTypes {
    POST_CREATED = 'POST_CREATED',
    COLLECTION_CREATED = 'COLLECTION_CREATED',
    NFT_MINTED = 'NFT_MINTED',
    NFT_LISTED = 'NFT_LISTED',
    BID_CREATED = 'BID_CREATED'
}
